# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-06 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(unique=True)),
                ('is_legacy', models.BooleanField()),
                ('is_import_destination', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
    ]
