# Generated by Django 2.1.1 on 2018-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fulfillmentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shopify_url_is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
