# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
                ('display_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=128)),
                ('style_number', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=64)),
                ('division', models.CharField(max_length=64)),
                ('available_start', models.DateField(blank=True, null=True)),
                ('available_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('archived', models.BooleanField()),
                ('brand_id', models.CharField(max_length=64)),
                ('wholesale_usd', models.PositiveIntegerField()),
                ('retail_usd', models.PositiveIntegerField()),
                ('wholesale_cad', models.PositiveIntegerField()),
                ('retail_cad', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=64)),
                ('colors', models.ManyToManyField(to='data_import.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('display_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.BigIntegerField(unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='data_import.Size'),
        ),
    ]
