# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_auto_20161124_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='inventory',
            field=models.SmallIntegerField(default=0),
        ),
    ]
