# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_variant_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retail_cad',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_usd',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_cad',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_usd',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
