# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_auto_20161129_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='display_name',
            new_name='_display_name',
        ),
    ]
