# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_auto_20161211_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropbox_id', models.CharField(max_length=64, unique=True)),
                ('path_lower', models.CharField(max_length=1024)),
                ('server_modified', models.DateTimeField()),
                ('company', models.CharField(max_length=64)),
                ('export_type', models.CharField(max_length=64)),
            ],
            options={
                'get_latest_by': 'server_modified',
            },
        ),
    ]
