# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_importfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='import_status',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('IN_PROGRESS', 'In Progress'), ('NOT_IMPORTED', 'Not Imported')], default='NOT_IMPORTED', max_length=16),
        ),
    ]
