# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_importfile_import_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='filename',
            field=models.CharField(default='no-filename', max_length=1024),
            preserve_default=False,
        ),
    ]
