# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_importfile_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='importfile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Company'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='export_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.ExportType'),
        ),
    ]
