# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0010_importfile_redis_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retail_cad',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_usd',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_cad',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_usd',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
