# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0013_remove_variant_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorNameCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect', models.CharField(max_length=64)),
                ('correct', models.CharField(max_length=64)),
            ],
        ),
    ]
