# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0014_colornamecorrection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='_display_name',
        ),
        migrations.AddField(
            model_name='color',
            name='momentis_name',
            field=models.CharField(default='color', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colornamecorrection',
            name='incorrect',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
