# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0015_auto_20170108_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(default='DEFAULT-SKU', max_length=265, unique=True),
            preserve_default=False,
        ),
    ]
