# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0016_variant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_correct',
            field=models.NullBooleanField(),
        ),
    ]
