# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0017_color_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='correction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_import.ColorNameCorrection'),
        ),
    ]
