# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0018_color_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shopify_api_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shopify_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shopify_shop_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
