# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0019_auto_20170409_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='should_import',
            field=models.BooleanField(default=False),
        ),
    ]
