# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-18 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_fulfillmentservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropbox_id', models.CharField(max_length=64, unique=True)),
                ('path_lower', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=1024)),
                ('server_modified', models.DateTimeField()),
                ('import_status', models.CharField(choices=[('IMPORTED', 'Imported'), ('IN_PROGRESS', 'In Progress'), ('NOT_IMPORTED', 'Not Imported'), ('EXPIRED', 'Expired')], default='NOT_IMPORTED', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('export_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropbox_import.ExportType')),
            ],
            options={
                'get_latest_by': 'server_modified',
            },
        ),
    ]
