# Generated by Django 2.1.1 on 2018-09-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropbox_import.ImportFile')),
            ],
        ),
        migrations.CreateModel(
            name='ImportJobLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropbox_import.ImportJob')),
            ],
        ),
    ]
