# Generated by Django 2.1.1 on 2018-09-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0002_importjob_importjoblogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Company'),
        ),
    ]
