# Generated by Django 2.1.1 on 2018-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0003_auto_20180924_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='celery_task_id',
            field=models.CharField(default='XXXXXX', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Job Running'), ('SUCCESS', 'Job Completed Successfully'), ('ERROR', 'Job Completed with Errors')], default='RUNNING', max_length=16),
        ),
    ]
