# Generated by Django 2.1.1 on 2018-09-25 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0004_auto_20180925_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
