# Generated by Django 2.1.1 on 2018-09-25 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0005_auto_20180925_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
