# Generated by Django 2.1.1 on 2018-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0006_auto_20180925_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='celery_task_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
