# Generated by Django 2.1.1 on 2018-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0007_auto_20180925_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Celery Task Not Started'), ('RUNNING', 'Celery Task Running'), ('SUCCESS', 'Job Completed Successfully'), ('ERROR', 'Job Completed with Errors')], default='NOT_STARTED', max_length=16),
        ),
    ]
