# Generated by Django 2.1.1 on 2018-10-08 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_import', '0008_auto_20181004_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AddField(
            model_name='importjoblogentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='importjoblogentry',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=16),
        ),
        migrations.AddField(
            model_name='importjoblogentry',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importjob',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('RUNNING', 'Running'), ('SUCCESS', 'Completed Successfully'), ('ERROR', 'Error - Not Completed')], default='NOT_STARTED', max_length=16),
        ),
    ]
